### ISSUE TITLE
Visualizer

### ISSUE THREAD

**Issue by WatermelonGD** [Flarewyre/SMBFunkMix#10]
Can you make the visualizer for the DX tracks public? Specifically the resolution where the pixels in the visualizer are 1 pixel wide in paint.net. I can't count the resolution. I'd assume it's around 112x63. The main one and the April Fools Sonic one. Thank you!

**Comment by Flarewyre** [comment]
https://files.catbox.moe/gbgb9m.pdn
here's the pdn used

**Comment by WatermelonGD** [comment]
Ok thanks
