### ISSUE TITLE
The sf2s for most of the flps are missing

### ISSUE THREAD

**Issue by WatermelonGD** [Flarewyre/SMBFunkMix#11]
When I load up a project, I get this error message.
![image](https://user-images.githubusercontent.com/104283079/166152568-16f13765-4b0c-4283-a26f-05f6ee6c3c6c.png)
Every project where juicysfplugin is there, this error appears.
And in most of the FLPs with Fruity Soundfont Player, the SF2 files necessary are missing.
![image](https://user-images.githubusercontent.com/104283079/166153038-295c7a38-1e3d-4134-9c15-ec384337dd74.png)
![image](https://user-images.githubusercontent.com/104283079/166153050-a8ea4bcd-d607-419a-90c4-2b235034d0cc.png)
Can you provide a fix for the juicysfplugin error and/or provide the missing sf2 files for the flps?

**Comment by Flarewyre** [comment]
just download juicysfplugin
as for the sf2s they aren't hard to find with some googling

**Comment by WatermelonGD** [comment]
I have juicysfplugin installed, and the main problem for the missing sf2s
is cake_dubstep_drums.sf2.
