### ISSUE TITLE
Hop-Hop Heights and Portal Power are missing in the FLPs.

### ISSUE THREAD

**Issue by CaptainGame17** [Flarewyre/SMBFunkMix#2]
I can understand why Portal Power is missing (perhaps fluffyhairs simply just doesn't release their FLPs,) but Hop-Hop Heights just seems more like an oversight, as its the only song by Krystal that is missing.

**Comment by Flarewyre** [comment]
the project file for hop hop heights got corrupted, so unfortunately i can't release it
as for portal power you're spot on
