### ISSUE TITLE
can't play the game 

### ISSUE THREAD

**Issue by ghost** [Flarewyre/SMBFunkMix#3]
![Screen Shot 2022-03-18 at 6 32 02 PM](https://user-images.githubusercontent.com/82131956/159101519-5bf1df15-ff79-4f63-84b5-0c85489bf16d.png)

**Comment by ghost** [comment]
this is the error that it is giving me please fix it

**Comment by mixerreq** [comment]
I have the same problem after compiling

**Comment by ghost** [comment]
i think you have to use the old 4.1.5 haxe version

**Comment by ghost** [comment]
for it to work

**Comment by mixerreq** [comment]
Ok i will try it

**Comment by ghost** [comment]
ok

**Comment by Flarewyre** [comment]
i probably should've updated before compiling, my bad
