### ISSUE TITLE
Green-Screen FLP soundfonts are missing/broken.

### ISSUE THREAD

**Issue by sweetcarolinaa** [Flarewyre/SMBFunkMix#6]
I'm fairly certain the soundfonts used in the song are either missing or using a broken vst that doesn't seem to want to load.
![image](https://user-images.githubusercontent.com/34987803/160309922-7241013e-a127-4ec4-a455-79227777cb9a.png)
The VST thing might not be as much of part of the issue, but it's still not provided what soundfont is used.

**Comment by a13fff** [comment]
thats a juicy problem most likely

**Comment by FnfMasterDom2** [comment]
yeah, um... i can't seem to get a nsmb sf2...
![green-screen flp - FL Studio 20 4_11_2022 3_32_44 PM](https://user-images.githubusercontent.com/93954676/162816411-043d7e9a-9eca-4daf-b942-07cd95592736.png)

**Comment by Flarewyre** [comment]
just google the name of the soundfont and you will find it https://musical-artifacts.com/artifacts/480
